---
Resources:
   MyEC2Instance1: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0e670eb768a5fc3d4"
      KeyName: "leo"
      InstanceType: "t2.micro"
      Tags:
        - Key: Name
          Value: MyEC2Instance1
    
    MyEC2Instance2: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0e670eb768a5fc3d4"
      KeyName: "leo"
      InstanceType: "t2.micro"
      Tags:
        - Key: Name
          Value: MyEC2Instance2

